"""
DGT Core Constants
System-wide constants for the DGT engine
"""

# Performance targets
TARGET_FPS = 60
FRAME_DELAY_MS = 1000 // TARGET_FPS

# Viewport dimensions (Game Boy parity)
TILE_SIZE_PIXELS = 8
VIEWPORT_WIDTH_PIXELS = 160
VIEWPORT_HEIGHT_PIXELS = 144
VIEWPORT_TILES_X = 20
VIEWPORT_TILES_Y = 18

# Display scaling
DISPLAY_SCALE = 4
DISPLAY_WIDTH_PIXELS = VIEWPORT_WIDTH_PIXELS * DISPLAY_SCALE
DISPLAY_HEIGHT_PIXELS = VIEWPORT_HEIGHT_PIXELS * DISPLAY_SCALE

# Update rates per display mode
TERMINAL_UPDATE_HZ = 10
COCKPIT_UPDATE_HZ = 30
PPU_UPDATE_HZ = 60

# Universal Packet limits
MAX_ENTITIES_PER_PACKET = 100
MAX_HUD_LINES = 4
MAX_PACKET_SIZE_KB = 1024  # 1MB max packet size

__all__ = [
    'TARGET_FPS', 'FRAME_DELAY_MS',
    'TILE_SIZE_PIXELS', 'VIEWPORT_WIDTH_PIXELS', 'VIEWPORT_HEIGHT_PIXELS',
    'VIEWPORT_TILES_X', 'VIEWPORT_TILES_Y', 'DISPLAY_SCALE',
    'DISPLAY_WIDTH_PIXELS', 'DISPLAY_HEIGHT_PIXELS',
    'TERMINAL_UPDATE_HZ', 'COCKPIT_UPDATE_HZ', 'PPU_UPDATE_HZ',
    'MAX_ENTITIES_PER_PACKET', 'MAX_HUD_LINES', 'MAX_PACKET_SIZE_KB'
]
